[project]
name = "clipboard-history"
version = "0.1.2"
description = "A clipboard history manager with infinite storage"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyqt6>=6.9.1",
    "winshell>=0.6",
]
